artery =c("Gja5","Cxcr4","Gja4","Hey1","Dll4","Jag1","Fbln5","Stmn2","Glul","Fos")
smc<-c("Myh11","Pdgfrb","Notch3","Myocd","Acta2")
cyc<-c("Top2a","Mki67","Birc5","Cenpa","Mcm4","Mcm6")
endomt <- c("Sox9","Mfap4","Pdgfra","Twist1","Serpine1")
endoec<-c("Npr3","Nfatc1","Tgfbi","Adgrg6","Snai1")
cap<-c("Aplnr","Car4","Aqp1","Rgcc","Aqp7")
CM<-c("Cdh2","Nkx2-5","Nppa","Actn2","Tbx5")

hspc.combined<-AddModuleScore(hspc.combined, features = list(artery,smc,cyc,endomt,endoec,cap,CM),name = c("artery","smc","cyc","endomt","endoec","cap","CM"), assay ="RNA")
FeaturePlot(hspc.combined,  features = "artery1", label = TRUE, repel = TRUE) 
FeaturePlot(hspc.combined,  features = "smc2", label = TRUE, repel = TRUE) 
FeaturePlot(hspc.combined,  features = "cyc3", label = TRUE, repel = TRUE) 
FeaturePlot(hspc.combined,  features = "endomt4", label = TRUE, repel = TRUE) 
FeaturePlot(hspc.combined,  features = "endoec5", label = TRUE, repel = TRUE) 
FeaturePlot(hspc.combined,  features = "cap6", label = TRUE, repel = TRUE) 
FeaturePlot(hspc.combined,  features = "CM7", label = TRUE, repel = TRUE) 
